"""Probe definition — what to check and how.

A Probe is a YAML file describing a health check. It has:
- A target (URL to check)
- Steps (browser actions to execute)
- Assertions (conditions that must be true)
- Output specs (artifacts to capture)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal


@dataclass
class Target:
    """What to check."""

    type: Literal["web"] = "web"
    url: str = ""

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Target:
        return cls(type=data.get("type", "web"), url=data.get("url", ""))


@dataclass
class Step:
    """A single browser action."""

    action: Literal["goto", "click", "type", "wait_for_selector", "wait_for_text"]
    url: str | None = None
    selector: str | None = None
    text: str | None = None
    value: str | None = None
    timeout_ms: int = 5000

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Step:
        return cls(
            action=data["action"],
            url=data.get("url"),
            selector=data.get("selector"),
            text=data.get("text"),
            value=data.get("value"),
            timeout_ms=data.get("timeout_ms", 5000),
        )


@dataclass
class Assertion:
    """A condition to verify after steps execute."""

    type: Literal[
        "selector_exists",
        "selector_count",
        "text_exists",
        "url_matches",
    ]
    selector: str | None = None
    text: str | None = None
    pattern: str | None = None
    min: int | None = None
    max: int | None = None
    extract: str = "text"  # "text", "html", "attr:href"

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Assertion:
        return cls(
            type=data["type"],
            selector=data.get("selector"),
            text=data.get("text"),
            pattern=data.get("pattern"),
            min=data.get("min"),
            max=data.get("max"),
            extract=data.get("extract", "text"),
        )


@dataclass
class OutputSpec:
    """What artifacts to capture."""

    type: Literal["screenshot", "html"]

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> OutputSpec:
        return cls(type=data["type"])


@dataclass
class Probe:
    """A probe definition — the central object.

    Probes can come from:
    - Hand-written YAML files
    - Imported from OpenCLI adapters (via adapters/opencli.py)
    - Imported from other adapter formats
    - Generated by `probelab init`
    """

    name: str
    description: str = ""
    target: Target = field(default_factory=Target)
    steps: list[Step] = field(default_factory=list)
    assertions: list[Assertion] = field(default_factory=list)
    outputs: list[OutputSpec] = field(default_factory=list)
    tags: list[str] = field(default_factory=list)
    timeout: int = 30
    browser: bool = False

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Probe:
        """Create a Probe from a parsed YAML/TOML dict."""
        target = Target.from_dict(data.get("target", {}))
        steps = [Step.from_dict(s) for s in data.get("steps", [])]
        assertions = [Assertion.from_dict(a) for a in data.get("assertions", [])]
        outputs = [OutputSpec.from_dict(o) for o in data.get("outputs", [])]

        # Auto-generate goto step if target has URL and no steps defined
        if target.url and not steps:
            steps = [Step(action="goto", url=target.url)]

        # Auto-detect browser need: if any step requires interaction, need browser
        browser = data.get("browser", False)
        interaction_actions = {"click", "type"}
        if any(s.action in interaction_actions for s in steps):
            browser = True

        return cls(
            name=data["name"],
            description=data.get("description", ""),
            target=target,
            steps=steps,
            assertions=assertions,
            outputs=outputs,
            tags=data.get("tags", []),
            timeout=data.get("timeout", 30),
            browser=browser,
        )

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a YAML-friendly dict."""
        result: dict[str, Any] = {"name": self.name}
        if self.description:
            result["description"] = self.description
        result["target"] = {"type": self.target.type, "url": self.target.url}
        if self.steps:
            result["steps"] = [
                {k: v for k, v in {
                    "action": s.action,
                    "url": s.url,
                    "selector": s.selector,
                    "text": s.text,
                    "value": s.value,
                    "timeout_ms": s.timeout_ms if s.timeout_ms != 5000 else None,
                }.items() if v is not None}
                for s in self.steps
            ]
        if self.assertions:
            result["assertions"] = [
                {k: v for k, v in {
                    "type": a.type,
                    "selector": a.selector,
                    "text": a.text,
                    "pattern": a.pattern,
                    "min": a.min,
                    "max": a.max,
                }.items() if v is not None}
                for a in self.assertions
            ]
        if self.outputs:
            result["outputs"] = [{"type": o.type} for o in self.outputs]
        if self.tags:
            result["tags"] = self.tags
        if self.timeout != 30:
            result["timeout"] = self.timeout
        if self.browser:
            result["browser"] = True
        return result
